-- Typipng practice

local phrases = {
    "The quick brown fox jumps over the lazy dog, while the sun sets behind the mountains, casting a golden glow across the serene landscape, perfect for a peaceful evening walk.",
    "Learning to type quickly and accurately is an essential skill in today's digital world, where communication and productivity rely heavily on efficient keyboard usage.",
    "Practice makes perfect, and with consistent effort, you can master touch typing, improving your speed and accuracy while reducing errors and increasing overall efficiency.",
    "Technology continues to evolve at a rapid pace, transforming the way we live, work, and interact, making adaptability and continuous learning crucial for success.",
    "Nature offers endless inspiration, from the vibrant colors of a sunset to the soothing sounds of a flowing river, reminding us to appreciate the beauty around us daily.",
    "Reading books expands your knowledge, enhances your vocabulary, and stimulates your imagination, making it a valuable habit for personal and professional growth.",
    "The world is full of diverse cultures, traditions, and perspectives, offering endless opportunities to learn, grow, and connect with people from all walks of life.",
    "Time management is a critical skill for achieving goals, balancing responsibilities, and maintaining a healthy work-life balance in today's fast-paced environment.",
    "Creativity thrives when you step out of your comfort zone, explore new ideas, and embrace challenges, leading to innovative solutions and personal fulfillment.",
    "Healthy habits, such as regular exercise, balanced nutrition, and adequate sleep, are essential for maintaining physical and mental well-being throughout your life.",
    "The developer spent hours debugging a race condition in their multithreaded Python script, muttering about GIL and async await syntax while refactoring callbacks.",
    "To optimize the SQL query, they added indexes, avoided nested loops, and used EXPLAIN ANALYZE, but the N+1 problem in the ORM layer still caused latency spikes.",
    "The React component's useEffect hook had unexpected side effects, triggering infinite re-renders until they added dependency arrays and memoized the state with Redux.",
    "Writing a Dockerfile for the Go microservice, they struggled with Alpine Linux dependencies, layer caching, and exposing ports while configuring the CI/CD pipeline.",
    "The machine learning engineer tuned hyperparameters, battled overfitting with dropout layers, and visualized gradients using TensorBoard, hoping the model would converge.",
    "In the code review, someone suggested replacing var with let, adding PropTypes, and fixing the eslint warnings about arrow functions returning implicit objects.",
    "The API returned a 429 Too Many Requests error, so they implemented exponential backoff with JWT authentication and rate limiting via Redis to throttle clients.",
    "After merging the feature branch, the Kubernetes pod crashed due to a memory leak, forcing them to check Prometheus metrics and adjust Helm chart resource limits.",
    "The regex pattern failed to match UTF-8 emojis in the user input, causing the JSON parser to throw a validation error during deserialization in the REST endpoint.",
    "They debated monorepos vs. polyrepos, configured Git hooks with Husky, and enforced commit message conventions to keep the project's history clean and semantic.",
    "The backend engineer struggled with PostgreSQL's deadlock detection, enabling log_lock_waits and tweaking deadlock_timeout while analyzing pg_stat_activity for blocked queries.",
    "Deploying a Rust microservice on AWS Lambda, they fought cold starts by compiling with --release and adjusting the provided concurrency, but async handlers still caused timeouts.",
    "The WebSocket handshake failed due to CORS policies; adding Sec-WebSocket-Protocol headers and configuring Nginx as a reverse proxy finally stabilized the real-time chat app.",
    "The blockchain dev wrote a Solidity smart contract for an ERC-20 token, testing edge cases with Hardhat, but gas optimization for transferFrom remained a pain point.",
    "A CSS grid layout broke in Safari due to vendor prefixes; they resorted to Flexbox fallbacks and added @supports queries, cursing browser inconsistencies.",
    "The GraphQL resolver for nested comments caused recursive over-fetching until they implemented DataLoader batching and added depth-limiting middleware to the Apollo Server.",
    "Debugging a memory fragmentation issue in C++, they switched from std::list to std::vector, used custom allocators, and analyzed VMMap outputs to reduce heap pressure.",
    "The Ansible playbook failed idempotency checks when templating nginx.conf, requiring changed_when overrides and atomic swaps with mv to avoid service restarts.",
    "The mobile team integrated Flutter's platform channels for native GPS access, but thread-safety issues in the Kotlin bridge caused sporadic ANRs on Android devices.",
    "Writing a GitHub Action for CI, they battled YAML's whitespace sensitivity, cache key patterns, and matrix jobs for cross-platform testing on macOS/Windows runners.",
    "Debugging a Lua plugin in Neovim, they traced nil errors to a missing __index metatable and fixed autocommands with vim.api.nvim_create_autocmd for buffer-specific logic.",
    "The game dev refactored Lua coroutines for NPC AI, avoiding deadlocks with coroutine.yield() and synchronizing state across LOVE2D's update/draw cycles.",
    "They patched a memory leak in a LuaJIT script by dereferencing C callbacks and avoiding FFI allocations in hot loops, boosting embedded system performance.",
    "A race condition emerged when Lua threads accessed a shared table; adding mutexes via lua_lock() and atomic swaps resolved the data corruption in the multiplayer game.",
    "The engineer wrote a Lua filter for Nginx, validating JWT tokens with ngx.re.match and caching results in shared dictionaries to reduce auth overhead.",
    "Profiling Lua code with jit.p showed excessive GC pauses, so they replaced ipairs with numeric for loops and pre-allocated tables for particle systems.",
    "In Roblox Studio, they debugged a Luau type mismatch using strict mode, then optimized physics with spatial partitioning and Instance:Clone() pooling.",
    "The config broke after upgrading LuaRocks; pinning dependency versions and rewriting C modules for Lua 5.4 compatibility fixed the segfaults in the CI pipeline.",
    "They built a DSL in Lua using metatables and setfenv, allowing runtime macros via loadstring while sandboxing unsafe ops for security-critical apps.",
    "A Lua script parsed 10GB logs with io.lines() and pattern captures, but pcall() was needed to handle malformed UTF-8 in the streaming data pipeline.",
}

return {
    {
        "nvzone/typr",
        dependencies = "nvzone/volt",
        opts = {
            wpm_goal = 50,
            phrases = phrases,
        },
        cmd = {"Typr", "TyprStats"},
    }
}
